swagger: '2.0'
info:
  description: CSRF Test API
  version: '1.0'
  title: CSRF Test API
paths:
  /csrf_test:
    post:
      summary: Perform a CSRF test
      description: Endpoint to perform a CSRF test on the provided target.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: target
          in: body
          description: Target URL for CSRF test
          required: true
          schema:
            type: object
            properties:
              target:
                type: string
      responses:
        '200':
          description: CSRF test result
          schema:
            type: object
            properties:
              result:
                type: string
definitions:
  Error:
    type: object
    properties:
      error:
        type: string
