swagger: '2.0'
info:
  title: Directory Bruteforce Test API
  description: Perform a directory brute force test on the provided target.
  version: '1.0'
paths:
  /dir_bruteforce:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - name: target
        in: formData
        type: string
        required: true
        description: The target URL to test.
      - name: wordlist
        in: formData
        type: file
        required: true
        description: Wordlist file for directory brute force test.
      - name: useragents_file
        in: formData
        type: file
        required: false
        description: File containing user-agents for directory brute force test.
      responses:
        '200':
          description: Directory brute force test result
          schema:
            type: object
            properties:
              result:
                type: string
