swagger: '2.0'
info:
  title: File Upload Test API
  description: Perform a file upload test on the provided target.
  version: '1.0'
paths:
  /file_upload_test:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - name: target
        in: formData
        type: string
        required: true
        description: The target URL to test.
      - name: upload_file
        in: formData
        type: file
        required: true
        description: File to upload.
      responses:
        '200':
          description: File upload test result
          schema:
            type: object
            properties:
              result:
                type: string
