# File: swagger/full_scan.yml
swagger: '2.0'
info:
  title: Full Scan API
  description: Perform a full scan including Nmap, XSS test, SQLi test, CSRF test,
    file upload test, privilege escalation test, rate limit test, and directory brute
    force test.
  version: '1.0'
paths:
  /full_scan:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - name: target
        in: formData
        type: string
        required: true
        description: The target URL or IP to scan.
      - name: param
        in: formData
        type: string
        required: true
        description: A parameter for SQLi test.
      - name: credentials
        in: formData
        type: string
        required: true
        description: Credentials for privilege escalation test.
      - name: wordlist
        in: formData
        type: file
        required: true
        description: Wordlist file for directory brute force test.
      - name: useragents_file
        in: formData
        type: file
        required: false
        description: File containing user-agents for directory brute force test.
      - name: upload_file
        in: formData
        type: file
        required: true
        description: File to upload for file upload test.
      - name: password_list_file
        in: formData
        type: file
        required: true
        description: Password list file for rate limit test.
      responses:
        '200':
          description: Full scan report
          schema:
            type: file
