# File: swagger/hello.yml
swagger: '2.0'
info:
  title: Hello API
  description: Example endpoint returning a hello message.
  version: '1.0'
paths:
  /hello:
    get:
      responses:
        '200':
          description: A simple hello message
          schema:
            type: object
            properties:
              message:
                type: string
                example: Hello, World!
