swagger: '2.0'
info:
  title: Privilege Escalation Test API
  description: Perform a privilege escalation test on the provided target.
  version: '1.0'
paths:
  /privilege_escalation_test:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: target
        in: body
        required: true
        schema:
          type: object
          properties:
            target:
              type: string
      - name: credentials
        in: body
        required: true
        schema:
          type: object
          properties:
            credentials:
              type: string
      responses:
        '200':
          description: Privilege escalation test result
          schema:
            type: object
            properties:
              result:
                type: string
