swagger: '2.0'
info:
  title: Rate Limit Test API
  description: Perform a rate limit and brute force test on the provided target.
  version: '1.0'
paths:
  /rate_limit_test:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: target
        in: body
        required: true
        schema:
          type: object
          properties:
            target:
              type: string
      - name: username
        in: body
        required: true
        schema:
          type: object
          properties:
            username:
              type: string
      - name: password_list_file
        in: formData
        type: file
        required: true
        description: Password list file for brute force.
      responses:
        '200':
          description: Rate limit and brute force test result
          schema:
            type: object
            properties:
              result:
                type: string
