swagger: '2.0'
info:
  title: SQLi Test API
  description: Perform an SQLi test on the provided target with a parameter.
  version: '1.0'
paths:
  /sqli_test:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: target
        in: body
        required: true
        schema:
          type: object
          properties:
            target:
              type: string
      - name: param
        in: body
        required: true
        schema:
          type: object
          properties:
            param:
              type: string
      responses:
        '200':
          description: SQLi test result
          schema:
            type: object
            properties:
              result:
                type: string
