swagger: '2.0'
info:
  title: XSS Test API
  description: Perform an XSS test on the provided target.
  version: '1.0'
paths:
  /xss_test:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: target
        in: body
        required: true
        schema:
          type: object
          properties:
            target:
              type: string
      responses:
        '200':
          description: XSS test result
          schema:
            type: object
            properties:
              result:
                type: string
